ARM64: configs: neternels_tbx304: Enable `CONFIG_BT_ATH3K`
Required to use some functions, as a workaround for:

  /home/hendramanudinata03/ANDROID/Kernels/NetErnels/android_kernel_lenovo_tbx304-nethunter/out/../drivers/bluetooth/btusb.c:2007: undefined reference to `get_rome_version'
  /home/hendramanudinata03/ANDROID/Kernels/NetErnels/android_kernel_lenovo_tbx304-nethunter/out/../drivers/bluetooth/btusb.c:2007:(.text+0x56ad5c): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `get_rome_version'
  /home/hendramanudinata03/ANDROID/Kernels/NetErnels/android_kernel_lenovo_tbx304-nethunter/out/../drivers/bluetooth/btusb.c:2016: undefined reference to `rome_download'
  /home/hendramanudinata03/ANDROID/Kernels/NetErnels/android_kernel_lenovo_tbx304-nethunter/out/../drivers/bluetooth/btusb.c:2016:(.text+0x56ada8): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `rome_download'

  drivers/built-in.o: In function `btusb_pm_notify':
  /home/hendramanudinata03/ANDROID/Kernels/NetErnels/android_kernel_lenovo_tbx304-nethunter/out/../drivers/bluetooth/btusb.c:2323: undefined reference to `btusb_pm_sem'
  /home/hendramanudinata03/ANDROID/Kernels/NetErnels/android_kernel_lenovo_tbx304-nethunter/out/../drivers/bluetooth/btusb.c:2323:(.text+0x56b288): relocation truncated to fit: R_AARCH64_ADR_PREL_PG_HI21 against undefined symbol `btusb_pm_sem'

Signed-off-by: Hendra Manudinata <hendra@manudinata.me>